# Generated by Django 4.2.8 on 2023-12-21 08:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statement', models.TextField(blank=True, default='', max_length=255)),
                ('sample_input', models.TextField(blank=True, default='', max_length=255)),
                ('sample_output', models.TextField(blank=True, default='', max_length=255)),
                ('hint', models.TextField(blank=True, default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='InputOutput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input', models.TextField(blank=True, default='', max_length=255)),
                ('output', models.TextField(blank=True, default='', max_length=255)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='outfile.problem')),
            ],
        ),
    ]
