# Generated by Django 4.2.8 on 2023-12-23 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outfile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='title',
            field=models.TextField(blank=True, default='', max_length=255),
        ),
    ]
